# Generated by Django 4.2.2 on 2023-06-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                ("StudentID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255, null=True)),
                ("LastName", models.CharField(max_length=255, null=True)),
                ("Title", models.CharField(max_length=255, null=True)),
                ("Matricule", models.CharField(max_length=255, null=True)),
                ("GroupMajor", models.CharField(max_length=255, null=True)),
                ("CellphoneNumber", models.CharField(max_length=255, null=True)),
                (
                    "StudentStatus",
                    models.CharField(
                        choices=[
                            ("Value1", "Value1"),
                            ("Value2", "Value2"),
                            ("Value3", "Value3"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("SpecialArrangement", models.CharField(max_length=255, null=True)),
                ("PersonalEmail", models.CharField(max_length=255, null=True)),
                ("SchoolEmail", models.CharField(max_length=255, null=True)),
                ("SchoolID", models.IntegerField(null=True)),
            ],
            options={
                "db_table": "students",
            },
        ),
    ]
