# Generated by Django 4.2.2 on 2023-06-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0001_initial"),
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                ("CourseID", models.AutoField(primary_key=True, serialize=False)),
                ("CourseName", models.CharField(max_length=255)),
                ("Subject", models.CharField(max_length=255)),
                ("Duration", models.IntegerField()),
                ("ListUpdatedDate", models.DateField()),
                ("SchoolYear", models.IntegerField()),
                ("Class", models.CharField(max_length=255)),
                (
                    "Level",
                    models.CharField(
                        choices=[
                            ("Value1", "Value1"),
                            ("Value2", "Value2"),
                            ("Value3", "Value3"),
                        ],
                        max_length=255,
                    ),
                ),
                ("InternalCourseCode", models.CharField(max_length=255)),
                (
                    "School",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teacher.school"
                    ),
                ),
                (
                    "Teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                    ),
                ),
            ],
        ),
    ]
