# Generated by Django 4.2.2 on 2023-06-14 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("SchoolID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Address", models.CharField(max_length=255)),
                ("City", models.CharField(max_length=255)),
                ("State", models.CharField(max_length=255)),
                ("Country", models.CharField(max_length=255)),
                ("ContactPerson", models.CharField(max_length=255)),
                ("ContactEmail", models.EmailField(max_length=254)),
                ("ContactPhone", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                ("TeacherID", models.AutoField(primary_key=True, serialize=False)),
                ("FirstName", models.CharField(max_length=255)),
                ("LastName", models.CharField(max_length=255)),
                ("Email", models.EmailField(max_length=254)),
                ("Phone", models.CharField(max_length=255)),
                ("Qualifications", models.CharField(max_length=255)),
                (
                    "School",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="teacher.school"
                    ),
                ),
            ],
        ),
    ]
